title: "Bayesian model diagnostics"
subtitle: "Workflows and software tools"
author:
  - name: "Noa Kallioinen"
    affiliation: University of Helsinki
  - name: "Osvaldo Martin"
    affiliation: Aalto University
  - name: "Teemu Säilynoja"
    affiliation: PyMC-Labs
format:
  revealjs:
    theme: [default, modern-glass.scss]
revealjs-plugins:
  - tabset
execute:
  cache: true
  freeze: auto