engine: jupyter
jupyter: python3

format:
  html:
    output-file: exercises-python.html
  ipynb:
    output-file: exercises-python.ipynb
    jupyter:
      kernelspec:
        display_name: python
        language: python
        name: jupyter